[tool.pyright]
exclude = ["build", "dist", "logs", ".venv"]

[tool.ruff]
ignore = ["E501", "F401"]

[tool.briefcase]
project_name = "ssiql"
bundle = "com.diegiwg"
version = "2.0.0"
url = "https://github.com/Diegiwg/ssiql"
license = "MIT license"
author = "Diegiwg (Diego Queiroz)"
author_email = "diegiwg@gmail.com"

[tool.briefcase.app.ssiql]
formal_name = "ssiql"
description = "Sales and Inventory System"
long_description = "This project is a system with a simplified interface that covers product and inventory control, including operations for product registration, listing, modification, and deletion. The project also includes a sales system where you can name the customer, select the payment method, and complete the purchase. Finally, there is an option to view sales that occurred on a specific date."
icon = "ssiql/resources/ssiql"
sources = ["ssiql"]
test_sources = ["tests"]

requires = ["tinydb==4.7.1"]

test_requires = ["pytest"]

[tool.briefcase.app.ssiql.macOS]
requires = ["toga-cocoa~=0.3.1", "std-nslog~=1.0.0"]

[tool.briefcase.app.ssiql.linux]
requires = ["toga-gtk~=0.3.1"]

[tool.briefcase.app.ssiql.linux.system.debian]
system_requires = [
    # Needed to compile pycairo wheel
    "libcairo2-dev",
    # Needed to compile PyGObject wheel
    "libgirepository1.0-dev",
]

system_runtime_requires = [
    # Needed to provide GTK
    "libgtk-3-0",
    # Needed to provide GI bindings to GTK
    "libgirepository-1.0-1",
    "gir1.2-gtk-3.0",
    # Needed to provide WebKit2 at runtime
    # "libwebkit2gtk-4.0-37",
    # "gir1.2-webkit2-4.0",
]

[tool.briefcase.app.ssiql.linux.system.rhel]
system_requires = [
    # Needed to compile pycairo wheel
    "cairo-gobject-devel",
    # Needed to compile PyGObject wheel
    "gobject-introspection-devel",
]

system_runtime_requires = [
    # Needed to support Python bindings to GTK
    "gobject-introspection",
    # Needed to provide GTK
    "gtk3",
    # Needed to provide WebKit2 at runtime
    # "webkit2gtk3",
]

[tool.briefcase.app.ssiql.linux.system.arch]
system_requires = [
    # Needed to compile pycairo wheel
    "cairo",
    # Needed to compile PyGObject wheel
    "gobject-introspection",
    # Runtime dependencies that need to exist so that the
    # Arch package passes final validation.
    # Needed to provide GTK
    "gtk3",
    # Dependencies that GTK looks for at runtime
    "libcanberra",
    # Needed to provide WebKit2
    # "webkit2gtk",
]

system_runtime_requires = [
    # Needed to provide GTK
    "gtk3",
    # Needed to provide PyGObject bindings
    "gobject-introspection-runtime",
    # Dependencies that GTK looks for at runtime
    "libcanberra",
    # Needed to provide WebKit2 at runtime
    # "webkit2gtk",
]

[tool.briefcase.app.ssiql.linux.appimage]
manylinux = "manylinux2014"

system_requires = [
    # Needed to compile pycairo wheel
    "cairo-gobject-devel",
    # Needed to compile PyGObject wheel
    "gobject-introspection-devel",
    # Needed to provide GTK
    "gtk3-devel",
    # Dependencies that GTK looks for at runtime, that need to be
    # in the build environment to be picked up by linuxdeploy
    "libcanberra-gtk3",
    "PackageKit-gtk3-module",
    "gvfs-client",
    # Needed to provide WebKit2 at runtime
    # "webkit2gtk3",
]
linuxdeploy_plugins = ["DEPLOY_GTK_VERSION=3 gtk"]

[tool.briefcase.app.ssiql.linux.flatpak]
flatpak_runtime = "org.gnome.Platform"
flatpak_runtime_version = "44"
flatpak_sdk = "org.gnome.Sdk"

[tool.briefcase.app.ssiql.windows]
requires = ["toga-winforms~=0.3.1"]

# Mobile deployments
[tool.briefcase.app.ssiql.iOS]
requires = ["toga-iOS~=0.3.1", "std-nslog~=1.0.0"]

[tool.briefcase.app.ssiql.android]
requires = ["toga-android~=0.3.1"]

# Web deployments
[tool.briefcase.app.ssiql.web]
requires = ["toga-web~=0.3.1"]
style_framework = "Shoelace v2.3"
