name: Build
on: [push]
jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Sync Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Libraries
        run: |
          pip install -r .\requirements-dev.txt
          briefcase create
          briefcase build -r
          briefcase package

      - name: Tree
        run: tree

      - name: Save Compiled Files
        uses: actions/upload-artifact@v3
        with:
          name: build_files_windows
          path: dist

  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Libraries
        run: |
          pip install -r ./requirements-dev.txt
          briefcase create
          briefcase build -r
          briefcase package

      - name: Tree
        run: tree

      - name: Save Compiled Files
        uses: actions/upload-artifact@v3
        with:
          name: build_files_linux
          path: dist
